import ascon
import param


def print_y39():
    print('set_point is: ' + str(ascon.query_rcu([param.Y39.set_point])))
    print('cabinet_temp is: ' + str(ascon.query_rcu([param.Y39.cabinet_temp])))
    print('evap_temp is: ' + str(ascon.query_rcu([param.Y39.evap_temp])))
    print('comp_status is: ' + str(ascon.query_rcu([param.Y39.comp_status])))
    print('defrost_status is: ' + str(ascon.query_rcu([param.Y39.defrost_status])))
    print('door_status is: ' + str(ascon.query_rcu([param.Y39.door_status])))
    print('high_temp_thresh is: ' + str(ascon.query_rcu([param.Y39.high_temp_thresh])))
    print('high_temp_delay is: ' + str(ascon.query_rcu([param.Y39.high_temp_delay])))
    print('restock_duration is: ' + str(ascon.query_rcu([param.Y39.restock_duration])))
    print('high_temp_defrost_delay is: ' + str(ascon.query_rcu([param.Y39.high_temp_defrost_delay])))
    print('rcu_memory_error is: ' + str(ascon.query_rcu([param.Y39.rcu_memory_error])))
    print('startup_timer is: ' + str(ascon.query_rcu([param.Y39.startup_timer])))
    print('ht_power_up_timer is: ' + str(ascon.query_rcu([param.Y39.ht_power_up_timer])))
    print('ht_timer is: ' + str(ascon.query_rcu([param.Y39.ht_timer])))
    print('ht_defrost_timer is: ' + str(ascon.query_rcu([param.Y39.ht_defrost_timer])))
    print('ht_restocking_timer is: ' + str(ascon.query_rcu([param.Y39.ht_restocking_timer])))
    print('door_open_alarm_delay is: ' + str(ascon.query_rcu([param.Y39.door_open_alarm_delay])))
    print('restocking_delay is: ' + str(ascon.query_rcu([param.Y39.restocking_delay])))
    print('buzzer is: ' + str(ascon.query_rcu([param.Y39.buzzer])))
    print('temp_units is: ' + str(ascon.query_rcu([param.Y39.temp_units])))
    print('firmware_release is: ' + str(ascon.query_rcu(param.Y39.firmware_release)))
    print('alert_mask is: ' + str(ascon.query_rcu(['207'])))


def print_x34():
    print('set_point is: ' + str(ascon.query_rcu([param.X34.set_point])))
    print('cabinet_temp is: ' + str(ascon.query_rcu([param.X34.cabinet_temp])))
    print('evap_temp is: ' + str(ascon.query_rcu([param.X34.evap_temp])))
    print('comp_status is: ' + str(ascon.query_rcu([param.X34.comp_status])))
    print('defrost_status is: ' + str(ascon.query_rcu([param.X34.defrost_status])))
    print('door_status is: ' + str(ascon.query_rcu([param.X34.door_status])))
    print('high_temp_thresh is: ' + str(ascon.query_rcu([param.X34.high_temp_thresh])))
    print('high_temp_delay is: ' + str(ascon.query_rcu([param.X34.high_temp_delay])))
    print('restock_duration is: ' + str(ascon.query_rcu([param.X34.restock_duration])))
    print('high_temp_defrost_delay is: ' + str(ascon.query_rcu([param.X34.high_temp_defrost_delay])))
    print('rcu_memory_error is: ' + str(ascon.query_rcu([param.X34.rcu_memory_error])))
    print('startup_timer is: ' + str(ascon.query_rcu([param.X34.startup_timer])))
    print('ht_power_up_timer is: ' + str(ascon.query_rcu([param.X34.ht_power_up_timer])))
    print('ht_timer is: ' + str(ascon.query_rcu([param.X34.ht_timer])))
    print('ht_defrost_timer is: ' + str(ascon.query_rcu([param.X34.ht_defrost_timer])))
    print('ht_restocking_timer is: ' + str(ascon.query_rcu([param.X34.ht_restocking_timer])))
    print('door_open_alarm_delay is: ' + str(ascon.query_rcu([param.X34.door_open_alarm_delay])))
    print('restocking_delay is: ' + str(ascon.query_rcu([param.X34.restocking_delay])))
    print('buzzer is: ' + str(ascon.query_rcu([param.X34.buzzer])))
    print('temp_units is: ' + str(ascon.query_rcu([param.X34.temp_units])))
    print('firmware_release is: ' + str(ascon.query_rcu([param.X34.firmware_release])))
    print('alert_mask is: ' + str(ascon.query_rcu(['207'])))
